SAMPLE_RATE = 16000
INPUT_AUDIO_QUEUE_MAX_SIZE = 120
INPUT_AUDIO_QUEUE_TIMEOUT_SECONDS = 0.2
PULSE_CAPTURE_BLOCK_SECONDS = 0.2
RECENT_TRANSCRIPT_WINDOW = 8
MAX_RECENT_SHORT_TEXT_REPEATS = 2
MAX_STAGED_SENTENCE_QUEUE = 12
NO_TEXT_STALE_STAGE_SUPPRESS_CHUNKS = 6
