from __future__ import annotations


def build_config(
    *,
    input_device: str,
    input_width: int,
    input_height: int,
    input_fps: int,
    output_device: str,
    output_width: int,
    output_height: int,
    output_fps: int,
    output_backend: str = "opencv",
    segmentation_backend: str,
    segmentation_threshold: float,
    segmentation_selfie_model_selection: int = 1,
    segmentation_selfie_temporal_smoothing: float = 0.25,
    segmentation_edge_smoothness: float = 0.5,
    segmentation_blend_feather: float = 0.35,
    background: dict,
    crop_margin: float,
    crop_pan_smoothing: float,
    crop_tilt_smoothing: float | None = None,
    crop_upper_body_bias: float = 0.0,
    crop_upper_body_ratio: float = 0.60,
    crop_upper_body_edge_smoothing: float = 0.35,
    input_software_zoom: float = 1.0,
    crop_zoom_smoothing: float = 0.80,
    crop_pan_pid_kp: float = 0.35,
    crop_pan_pid_ki: float = 0.01,
    crop_pan_pid_kd: float = 0.12,
    crop_tilt_pid_kp: float | None = None,
    crop_tilt_pid_ki: float | None = None,
    crop_tilt_pid_kd: float | None = None,
    crop_pan_target_offset_x: float = 0.0,
    crop_pan_target_offset_y: float = 0.0,
    audio_enabled: bool = True,
    audio_input_device: str = "default",
    audio_output_device: str = "default",
    audio_sample_rate: int = 48000,
    audio_channels: int = 1,
    audio_frame_ms: int = 20,
    audio_denoise_enabled: bool = True,
    audio_denoise_backend: str = "none",
    audio_denoise_strength: float = 0.5,
    audio_gate_enabled: bool = True,
    audio_gate_threshold_db: float = -40.0,
    audio_gate_hysteresis_db: float = 4.0,
    audio_gate_attack_ms: int = 30,
    audio_gate_hold_ms: int = 160,
    audio_gate_release_ms: int = 500,
    audio_gate_open_gain: float = 1.0,
    audio_gate_closed_gain: float = 0.0,
    audio_gate_min_voice_band_ratio: float = 0.50,
) -> dict:
    tilt_smoothing = float(crop_pan_smoothing if crop_tilt_smoothing is None else crop_tilt_smoothing)
    tilt_kp = float(crop_pan_pid_kp if crop_tilt_pid_kp is None else crop_tilt_pid_kp)
    tilt_ki = float(crop_pan_pid_ki if crop_tilt_pid_ki is None else crop_tilt_pid_ki)
    tilt_kd = float(crop_pan_pid_kd if crop_tilt_pid_kd is None else crop_tilt_pid_kd)
    return {
        "inputCamera": {
            "devicePath": input_device,
            "width": input_width,
            "height": input_height,
            "fps": input_fps,
            "crop": {"x": 0, "y": 0, "width": input_width, "height": input_height},
            "softwareZoom": float(input_software_zoom),
        },
        "outputCamera": {
            "devicePath": output_device,
            "width": output_width,
            "height": output_height,
            "fps": output_fps,
            "backend": output_backend,
        },
        "segmentation": {
            "backend": segmentation_backend,
            "threshold": segmentation_threshold,
            "edgeSmoothness": float(segmentation_edge_smoothness),
            "blendFeather": float(segmentation_blend_feather),
            "selfie": {
                "modelSelection": int(segmentation_selfie_model_selection),
                "temporalSmoothing": float(segmentation_selfie_temporal_smoothing),
            },
        },
        "background": background,
        "crop": {
            "margin": crop_margin,
            "panSmoothing": crop_pan_smoothing,
            "tiltSmoothing": tilt_smoothing,
            "upperBodyBias": float(crop_upper_body_bias),
            "upperBodyRatio": float(crop_upper_body_ratio),
            "upperBodyEdgeSmoothing": float(crop_upper_body_edge_smoothing),
            "zoom": float(input_software_zoom),
            "zoomSmoothing": float(crop_zoom_smoothing),
            "panPidKp": float(crop_pan_pid_kp),
            "panPidKi": float(crop_pan_pid_ki),
            "panPidKd": float(crop_pan_pid_kd),
            "tiltPidKp": tilt_kp,
            "tiltPidKi": tilt_ki,
            "tiltPidKd": tilt_kd,
            "panTargetOffsetX": float(crop_pan_target_offset_x),
            "panTargetOffsetY": float(crop_pan_target_offset_y),
        },
        "audio": {
            "enabled": bool(audio_enabled),
            "inputDevice": audio_input_device,
            "outputDevice": audio_output_device,
            "sampleRate": int(audio_sample_rate),
            "channels": int(audio_channels),
            "frameMs": int(audio_frame_ms),
            "denoise": {
                "enabled": bool(audio_denoise_enabled),
                "backend": str(audio_denoise_backend),
                "strength": float(audio_denoise_strength),
            },
            "gate": {
                "enabled": bool(audio_gate_enabled),
                "thresholdDb": float(audio_gate_threshold_db),
                "hysteresisDb": float(audio_gate_hysteresis_db),
                "attackMs": int(audio_gate_attack_ms),
                "holdMs": int(audio_gate_hold_ms),
                "releaseMs": int(audio_gate_release_ms),
                "openGain": float(audio_gate_open_gain),
                "closedGain": float(audio_gate_closed_gain),
                "minVoiceBandRatio": float(audio_gate_min_voice_band_ratio),
            },
        },
    }
